### ISSUE TITLE
Not working properly.

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/susi_desktop#11]
For some reason this app is not working properly. Sometimes it gives some strange answers and sometimes it's not even answering. We need to find out the problem and solve it.

**Comment by BrainBuzzer** [comment]
I am working on it. Reply is getting cached, due to which, providing same answers for several times.

**Comment by ankitrgadiya** [comment]
Oh cool

**Comment by Orbiter** [comment]
when I tested this, it always gave me answers on my previous question, not the latest question.

**Comment by anshumanv** [comment]
The app is functional now, so this can be closed.
