### ISSUE TITLE
Port app to Aurelia

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_desktop#12]
There are so many bugs coming in the way like #11 which makes chat experience really bad. The goal is to port this app to Aurelia which already uses latest JavaScript i.e. ES2016 and has pretty things coming around it. While the app is still in early stages, it will be good enough to port it to some application framework right now. Afterwards, it will be really complex job to do so.

**Comment by ankitrgadiya** [comment]
@BrainBuzzer Can we not fix the bugs in current version. I'm sure Electron can do that afterall slack clients are also using Electron.  
Talking about Aurelia, I'm not very much aware of it and how it works. Lets take others opinion.

@mariobehling @daminisatya  What do you guys think about it?

**Comment by BrainBuzzer** [comment]
It is almost JavaScript but just based on latest versions. Though slack is based on Electron, let's not forget that anything that we make in Electron is equivalent to a website. Using Aurelia will help in clearing out some of the bugs. 

@ankitrgadiya Don't worry, it is just JavaScript. If you are comfortable with Java, Python, PHP - OOP, you are mostly comfortable there. It just allows some more options like Dependency Injection, Asynchronus loading, little better environment for chat UI.

**Comment by mariobehling** [comment]
There is no reason, why there should not be two implementations of a Desktop app.

@BrainBuzzer If others do not feel comfortable with Aurelia, I think they would not contribute so much. So, I suggest we start another Susi_Aurelia repo. What do you think?

**Comment by ankitrgadiya** [comment]
@mariobehling Yeah I'm not comfortable with javascript and aurelia but we're here to learn so. I have no problem in porting. Just that I'll not be able to contribute during the starting phase.

**Comment by BrainBuzzer** [comment]
Yeah, that will be quite good. I can understand that most of these repos are targeting for contribution from beginners in Open Source. Please create a new repo because I have almost completed work on it. I will try to push all that code to that repo and this repo will just be vanilla JS.
