### ISSUE TITLE
Add animation to AutoScroll

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_desktop#14]
Currently, autoscroll doesn't seem like it is actually scrolling. Adding a little animation to it would be amazing. @ankitrgadiya Would you like to work on this?

**Comment by ankitrgadiya** [comment]
@BrainBuzzer I don't know much about javascript as of now. Sorry

**Comment by BrainBuzzer** [comment]
Alright, I will try to do that myself

**Comment by BrainBuzzer** [comment]
@djmgit Would you like to work on this?

**Comment by djmgit** [comment]
@BrainBuzzer Okay, I will try
