### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_desktop#35]
currently Default electronJS icon is used. It should be changed to SUSI Icon.

**Comment by BrainBuzzer** [comment]
Would you like to work on this task?

**Comment by dynamitechetan** [comment]
I tried but stuck on cross platform issue. Every platform accepts icon in a different extention. 
I will try to work on this.

**Comment by BrainBuzzer** [comment]
I guess `.ico` is universally accepted.

**Comment by dynamitechetan** [comment]
.ico is for windows, pngs for ubuntu and .icns file for mac.
This is what I read.
