### ISSUE TITLE
Add building script

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/susi_desktop#37]
Currently, there is no building script in `package.json` file. It would be great if there will be a script to build the application for all platforms.

**Comment by Orbiter** [comment]
If possible, create packages for Windows and Mac, so end-users are able to install this without knowledge about node/electron

**Comment by anshumanv** [comment]
@Orbiter I will do the needful shortly and generate installers for all platforms, also a feature to fire the desktop app from terminal can be implemented after publishing this app as an npm module itself !
