### ISSUE TITLE
Add travis CI for improved code quality

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_desktop#40]
Adding travis CI to the repo will help reviewers to get their work done quickly and will lead to agile development of the project.

**Comment by aviaryan** [comment]
For starters, we can use ESLint with Airbnb preset to check style using Travis.
https://github.com/airbnb/javascript/blob/master/linters/.eslintrc

A much better solution will be using a code review platform like Codacy though. I wonder if we can make it support Airbnb style.

**Comment by anshumanv** [comment]
I was thinking of porting to xo code style, views @aviaryan ?

**Comment by anshumanv** [comment]
xo is based on ESLint so that should suffice i think, also it's inclusion is easy.

**Comment by aviaryan** [comment]
The good thing about [xo](https://github.com/sindresorhus/xo) is that it is fast, beautiful and has good text editor plugins. 

I don't have any preference for a style guide but the important thing is that we should religiously stick to a guideline. So if you want, let's go with xo. It's still very early in the project so damage will be done with this switch. @mariobehling What do you think?

**Comment by anshumanv** [comment]
We need to remake the entire project anyways since the current code doesn't give correct results also the chat.susi.ai webapp will be used in a webview tag.
