### ISSUE TITLE
Implement Auto-scroll

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/susi_desktop#5]
Currently it works like this:
We type message and click send button.
The message is added in conversation but the app is still on last message.
Then we have to scroll to the bottom to see the latest message.

Ideally: 
We enter message and the app should automatically scroll to the bottom.

**Comment by BrainBuzzer** [comment]
Are you working on this?

**Comment by ankitrgadiya** [comment]
No I'm not. Go for it.
