### ISSUE TITLE
Add new loader gif

### ISSUE THREAD

**Issue by tstreamDOTh** [fossasia/susi_desktop#82]
**Actual Behaviour**

Currently, the loader gif seems irrelevant

**Expected Behaviour**

Add a relevant loader which suits the application and SUSI them overall

**Would you like to work on this?**
Yes

**Comment by anshumanv** [comment]
Please go ahead, @tstreamDOTh 👍

**Comment by tstreamDOTh** [comment]
I will make one

**Comment by anshumanv** [comment]
Alright, exactly what I wanted. 😄

**Comment by anshumanv** [comment]
How is this coming along @tstreamDOTh? :smile:

**Comment by tstreamDOTh** [comment]
@anshumanv Was working on other issues. Will make a PR this weekend.

**Comment by anshumanv** [comment]
Awesome! Thanks :+1:
